CREATE TABLE  AVD.TEST.SAMPLE_DATA AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

SELECT * FROM AVD.TEST.SAMPLE_DATA LIMIT 10;


-- PUT file://C:\Users\Amey\Downloads\ord.csv @MY_STAGE; CLI COMMAND AND DISPLAY 
SELECT $1 
FROM @AVD.TEST.MY_STAGE


-- CREATE TABLE SAME SCHEMA 
CREATE TABLE ORDER_DEMO(
    ORDER_ID STRING,
    AMOUNT FLOAT,
    PROFIT FLOAT,
    QUANTITY INT,
    CATEGORY STRING,
    SUBCATEGORY STRING
);

SELECT * FROM AVD.TEST.ORDER_DEMO;

SELECT CONCAT($1,'_ORD') AS ORDER_ID,
    $2 AS AMOUNT,
    $3 AS PROFIT,
    $5 AS CATEGORY
FROM @AVD.TEST.MY_STAGE
(FILE_FORMAT => CSV_FORMAT);


-- FILE FORMATTING 
CREATE FILE FORMAT CSV_FORMAT
    TYPE = CSV 
    SKIP_HEADER = 1
    SKIP_BLANK_LINES = TRUE;
    
-- Total profit for each CATEGORY

SELECT $5 AS CATEGORY,
    SUM($3) AS TOTAL_PROFIT
FROM @AVD.TEST.MY_STAGE
(FILE_FORMAT => CSV_FORMAT)
GROUP BY $5;

-- COPY INTO + Transformation

CREATE TABLE AVD.TEST.ORDERS_TRANSFORMED (
    ORDER_ID STRING,
    PROFIT FLOAT,
    CATEGORY STRING
);

COPY INTO AVD.TEST.ORDERS_TRANSFORMED
    (ORDER_ID , PROFIT ,CATEGORY )
FROM ( SELECT
        CONCAT($1, '_ORD') AS ORDER_ID,
    $3 AS PROFIT , 
    $5 AS CATEGORY
    FROM  @AVD.TEST.MY_STAGE
)
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM AVD.TEST.ORDERS_TRANSFORMED
-- table of prfit > 500 and copy data 
CREATE table AVD.TEST.PROFITABLE_ORDERS(
ORDER_ID string,  
PROFIT float, 
CATEGORY string 
);


copy into AVD.TEST.PROFITABLE_ORDERS( ORDER_ID, PROFIT, CATEGORY)
from( 
    SELECT
        CONCAT($1, '_ORD') AS ORDER_ID,
        $3 AS PROFIT,
        $5 AS CATEGORY
    FROM @AVD.TEST.MY_STAGE
    WHERE $3 > 500
)
FILE_FORMAT = CSV_FORMAT;

copy into avd.test.profitable_orders(ORDER_ID,PROFIT , CATEGORY)
FROM (
SELECT
    CONCAT($1, '_ORD') AS ORDER_ID,
    $3 AS PROFIT,
    $5 AS CATEGORY
FROM @AVD.TEST.MY_STAGE/ord.csv
WHERE $3 > 500)
FILE_FORMAT = CSV_FORMAT

-- donr for csv now for json 
list @AVD.TEST.MY_STAGE

select $1
from @AVD.TEST.MY_STAGE/orders.json.gz
(FILE_FORMAT => JSON_FORMAT);


-- JSON FILE FORMATTING 
CREATE FILE FORMAT AVD.TEST.JSON_FORMAT
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE;


SELECT
  $1:ORDER_ID::STRING as order_id,
  $1:AMOUNT::float as amount,
  $1:PROFIT::float as profit,
  $1:QUANTITY::INT quantity ,
  $1:CATEGORY::STRING category ,
  $1:SUBCATEGORY::STRING as sub_category 
FROM @AVD.TEST.MY_STAGE/orders.json.gz
(FILE_FORMAT => JSON_FORMAT)
  
