-- SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS LOCATION 
SELECT CURRENT_DATABASE(),CURRENT_SCHEMA()
-- USE DB AND SCHEMA 
USE DATABASE AVD
USE SCHEMA AVD.TEST

-- CREATE SEQUENCE 
CREATE SEQUENCE SEQ1
START = 1000
INCREMENT = 1
ORDER;

-- DISPLAY SEQUENCE NAME 
SHOW SEQUENCES IN SCHEMA AVD.TEST;

-- SELECT QUERY TO DISPLAY NEXTVAL TILL 5 
SELECT AVD.TEST.SEQ1.NEXTVAL; -- DISPLAY 1 VAL AND INCREMENT 
SELECT AVD.TEST.SEQ1.NEXTVAL
FROM TABLE(GENERATOR(ROWCOUNT => 5));

SELECT AVD.TEST.SEQ1.NEXTVAL;

-- AVD.TEST.EMPLOYEE CRETAE TABLE WITH AUTOINCRMNT AND START WITH 100 AND INCRMNT 1 
CREATE OR REPLACE TABLE AVD.TEST.EMPLOYEE(
EMP_ID INT AUTOINCREMENT START 100 INCREMENT 1,
EMP_NAME STRING,
DAPARTMENT STRING, 
SALARY FLOAT 
)

-- INSERT 3 ROWS 

INSERT INTO AVD.TEST.EMPLOYEE
    (EMP_NAME, DAPARTMENT, SALARY)
VALUES
    ('AMEY', 'DE', 99000),
    ('RAJ', 'DE', 99000),
    ('SUYESH', 'DE', 99000);

SELECT * FROM AVD.TEST.EMPLOYEE

-- CREATE 2ND TABLE AVD.TEST.EMPLOYEE2 
-- AUTO_INCREMENT

CREATE OR REPLACE TABLE AVD.TEST.EMPLOYEE2(
EMP_ID INT AUTOINCREMENT START 1000 INCREMENT 5,
EMP_NAME STRING,
DEPARTMENT STRING, 
SALARY FLOAT 
)

INSERT INTO AVD.TEST.EMPLOYEE2
    (EMP_NAME,DEPARTMENT,SALARY)
VALUES
    ('AMEY','DS',98000),
    ('SARVESH','DR',90000),
    ('SOHAM','IT',89000),
     ('SHIV','DR',90000),
    ('PUMPU','IT',89000)

SELECT * FROM AVD.TEST.EMPLOYEE2

INSERT INTO AVD.TEST.EMPLOYEE2
    (EMP_NAME,DEPARTMENT,SALARY)
VALUES
    ('SAM','DS',98000),
    ('OM','DR',90000) 

DELETE FROM AVD.TEST.EMPLOYEE2
WHERE EMP_ID = (
    SELECT MAX(EMP_ID)
    FROM AVD.TEST.EMPLOYEE2
);

SELECT * FROM AVD.TEST.EMPLOYEE2
-- If 1030 was deleted, Snowflake will not reuse 1030. It moves to the next generated value, 1035.

INSERT INTO AVD.TEST.EMPLOYEE2
    (EMP_NAME, DEPARTMENT, SALARY)
VALUES
    ('NEW_EMP', 'DS', 95000);
    
SELECT * FROM AVD.TEST.EMPLOYEE2

--Create two sequences: ORDER vs NOORDER
CREATE SEQUENCE S1
START = 100
INCREMENT = 1
ORDER;

SELECT AVD.TEST.S1.NEXTVAL
FROM TABLE(GENERATOR(ROWCOUNT => 10))


CREATE SEQUENCE S2
START = 100
INCREMENT = 1
NOORDER;

SELECT AVD.TEST.S2.NEXTVAL
FROM TABLE(GENERATOR(ROWCOUNT => 10))

SHOW SEQUENCES IN SCHEMA AVD.TEST;

-- Configurable Sequence

CREATE SEQUENCE S3
START = 500
INCREMENT = 25 
ORDER;

SHOW SEQUENCES IN SCHEMA AVD.TEST

SELECT AVD.TEST.S3.NEXTVAL
FROM TABLE(GENERATOR(ROWCOUNT => 6))

ALTER SEQUENCE S3 SET INCREMENT = 100 

