CREATE SCHEMA MY_VIEWS

-- SELECT DATA 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER LIMIT 50

-- JOIN 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER AS C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION AS N
ON C.C_NATIONKEY = N.N_NATIONKEY
WHERE N.N_NAME = 'BRAZIL';

-- VIEW 
CREATE OR REPLACE VIEW  AVD.MY_VIEWS.CUSTOMER_VIEW
AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER AS C
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION AS N
    ON C.C_NATIONKEY = N.N_NATIONKEY
    WHERE N.N_NAME = 'BRAZIL';

-- DISPLAY VIEW 
SELECT * FROM AVD.MY_VIEWS.CUSTOMER_VIEW;
-- DISPLAY VIEW IN SCHMEA TOTAL VIEW 
SHOW VIEWS IN SCHEMA MY_VIEWS
===============================================================================================================

-- CREATE SECURE VIEW 
SELECT C.C_CUSTKEY, 
C.C_NAME, 
N.n_nationkey,
R.R_NAME
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER AS C
JOIN 
SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION AS N
ON 
C.C_NATIONKEY = N.N_NATIONKEY
JOIN
SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION AS R 
ON 
R.R_REGIONKEY = N.N_REGIONKEY
WHERE 
R.R_NAME = 'AMERICA';

CREATE OR REPLACE SECURE VIEW AVD.MY_VIEWS.REGION_VIEW 
AS 
SELECT C.C_CUSTKEY, 
C.C_NAME, 
N.n_nationkey,
R.R_NAME
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER AS C
JOIN 
SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION AS N
ON 
C.C_NATIONKEY = N.N_NATIONKEY
JOIN
SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION AS R 
ON 
R.R_REGIONKEY = N.N_REGIONKEY
WHERE 
R.R_NAME = 'AMERICA'

-- GIVE ACCESS TO PUBLIC THEN 
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PUBLIC;
GRANT USAGE ON DATABASE AVD TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA MY_VIEWS TO ROLE PUBLIC;


GRANT SELECT ON VIEW MY_VIEWS.REGION_VIEW TO ROLE PUBLIC;

-- THEN GO TO PUBLIC ACCOUNT 
=====================================================================================================
-- MATERIALIZED VIEW 
-- DIS ADV // CREATE MATERIALIZED VIEW
-- NOTE 
-- i.YOU CAN'T USE MULTIPLE TABLES, YOU CAN USE ONLY ONE TABLE.
-- ii.IT DOES NOT SUPPORT JOINS, EVEN SELF JOINS ARE NOT SUPPORTED.
-- iii.A MATERIALIZED VIEW CANNOT QUERY ANOTHER VIEW OR ANOTHER MATERIALIZED VIEW OR A UDF.
-- iv. IT DOES NOT SUPPORT ALL AGGREGATION AND WINDOW FUNCTION.
-- v. MATERIALIZED VIEWS ARE ONLY AVAILABLE IN ENTERPRISE AND BUSINESS CRITICAL EDITIONS, THEY ARE NOT AVAILABLE IN STANDARD EDITION.

CREATE OR REPLACE MATERIALIZED VIEW AVD.MY_VIEWS.CUSTOMER_MATERIALIZED_VIEW
AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS
    WHERE SUBSTR(O_ORDERPRIORITY, 1, 1) = '2'
    AND YEAR(O_ORDERDATE) = 1992 AND MONTH(O_ORDERDATE) = 7;
    

SELECT * FROM AVD.MY_VIEWS.CUSTOMER_MATERIALIZED_VIEW
