CREATE TABLE EMP(
NAME_1 CHAR(5),
NAME_2 VARCHAR(5)
);
INSERT INTO EMP VALUES ('A','A');
SELECT LENGTH (NAME_1) ,LENGTH(NAME_2) FROM EMP;
SET SESSION SQL_MODE = 'PAD_CHAR_TO_FULL_LENGTH'; -- RUN THESE FIRST 


CREATE TABLE BLOG(
ID INT,
TITLE VARCHAR(30),
CONTENT TEXT

);
INSERT  INTO BLOG VALUES (1,'KJBEVEJVBKEJV','KJBEVKBEJVKBKEVEJKVBEKVJBERKVBEKVBR'); 
SELECT * FROM BLOG;


CREATE TABLE INTU( X INT );
INSERT INTO INTU VALUES (1),(1.2),(1.5),(1.8);
SELECT * FROM INTU;

CREATE TABLE PONEG( 
X INT,
Y INT SIGNED,
Z INT UNSIGNED

);

INSERT INTO PONEG VALUES (1,2,3),(2,-3,0);
INSERT INTO PONEG VALUES (-1,-2,-3);
SELECT * FROM PONEG;


CREATE TABLE PAISA (SALARY DECIMAL(8,2));
INSERT INTO PAISA VALUES ('123456.345');
SELECT * FROM PAISA;


CREATE TABLE POMPESH ( 
PRICE_1 FLOAT,
PRICE_2 DECIMAL(10,2));

INSERT INTO POMPESH VALUES (0.1,0.1);
SELECT * FROM POMPESH;
SELECT
FORMAT(PRICE_1,20) AS FLOAT_VALUE ,
FORMAT(PRICE_2,20) AS DECIMAL_VALUE
FROM POMPESH;


CREATE TABLE VEDANT(
EMP_1 INT,
JOINING_DATE DATE,
LOGIN_DATE  TIME,
MEETING_DATE DATETIME,
CREATED_AT TIMESTAMP );

INSERT INTO VEDANT VALUES (1,'2026-10-02','09:30:45','2026-10-02 10:00:00',CURRENT_TIMESTAMP);

SELECT * FROM VEDANT;

CREATE TABLE TUMTUM(
ID INT,
NAME VARCHAR(49),
ADDR_JSON JSON);

DESC TUMTUM;
SELECT * FROM TUMTUM;
INSERT INTO TUMTUM VALUES (1,'A', '{ "STATE":"MAHARASHTRA","CITY":"PUNE"}');

SELECT * FROM TUMTUM 
WHERE 
ADDR_JSON ->> '$.CITY' = 'PUNE';

SELECT 
ID,
NAME,
ADDR_JSON ->> '$.CITY' AS CITY,
ADDR_JSON ->> '$.STATE' AS STATE
FROM TUMTUM 
WHERE ADDR_JSON ->> '$.CITY'='PUNE';


