SHOW DATABASES;
USE AMU;
CREATE DATABASE IF NOT EXISTS COMPANY_DB;
USE COMPANY_DB;
CREATE TABLE EMPLOYEEEE(
ID INT,
NAME VARCHAR(40),
DEPARTMENT VARCHAR(30),
SALARY INT,
CITY VARCHAR(30)
);

SELECT * FROM EMPLOYEEEE;

ALTER TABLE EMPLOYEEEE ADD EMAIL VARCHAR(50);
ALTER TABLE EMPLOYEEEE CHANGE DEPARTMENT DEPT VARCHAR(50);
ALTER TABLE EMPLOYEEEE DROP EMAIL;


INSERT INTO EMPLOYEEEE VALUE (101,'RAHUL','IT',50000,'PUNE');
INSERT IGNORE INTO EMPLOYEEEE 
VALUE 
(101,'RAHUL','IT',50000,'PUNE'),
(102,'SNEHA','HR',45000,'MUMBAI'),
(103,'AMIT','FINANCE',60000,'DELHI'),
(104,'PRIYA','IT',70000,'PUNE'),
(105,'KARAN','SALES',40000,'NAGPUR');


UPDATE EMPLOYEEEE SET SALARY = 55000 WHERE ID = 101;
DELETE FROM EMPLOYEEEE WHERE ID = 105;

TRUNCATE TABLE EMPLOYEEEE;
DROP TABLE EMPLOYEEEE;

START TRANSACTION; 
 DELETE FROM EMPLOYEEEE;
 ROLLBACK;
 
 SELECT NAME,CITY FROM EMPLOYEEEE WHERE CITY = 'PUNE';
 SELECT NAME,SALARY FROM EMPLOYEEEE WHERE SALARY > 50000;
 SELECT NAME,SALARY FROM EMPLOYEEEE WHERE SALARY BETWEEN 45000 AND 65000;
 SELECT NAME,DEPARTMENT FROM EMPLOYEEEE WHERE DEPARTMENT = 'IT';
 SELECT NAME FROM EMPLOYEEEE WHERE NAME LIKE 'P%';
 SELECT NAME FROM EMPLOYEEEE WHERE NAME LIKE '%A';
 SELECT NAME FROM EMPLOYEEEE WHERE NAME LIKE '%MI%';

 SELECT * FROM EMPLOYEEEE ORDER BY SALARY DESC; 
 SELECT DISTINCT DEPARTMENT FROM EMPLOYEEEE;
 SELECT NAME,CITY FROM EMPLOYEEEE WHERE CITY = 'PUNE' OR CITY ='MUMBAI';
 SELECT NAME,SALARY,CITY FROM EMPLOYEEEE WHERE SALARY > 60000 AND CITY = 'PUNE';
 SELECT * FROM EMPLOYEEEE WHERE ID= 101 OR ID = 103 OR ID = 105 ; 
 
 CREATE TABLE EMPLOY AS SELECT * FROM EMPLOYEEEE;
 SELECT * FROM EMPLOY1;
 
 CREATE TABLE EMPLOY1 LIKE EMPLOYEEEE;
  SELECT * FROM EMPLOY1;
INSERT INTO EMPLOY1 SELECT * FROM EMPLOYEEEE WHERE CITY = 'PUNE';

