CREATE TABLE EMPL_DATA(
EMP_ID INT,
EMP_NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
CITY VARCHAR(50),
SALARY DECIMAL(10,2),
BONUS DECIMAL(10,2),
EXPERIENCE INT,
JOIN_DATE DATE,
MANAGER_ID INT,
STATUS VARCHAR(20)

);

INSERT INTO EMPL_DATA VALUES
(101,'Rahul','IT','Pune',60000,5000,3,'2022-01-15',201,'Active'),
(102,'Sneha','HR','Mumbai',45000,NULL,2,'2023-03-20',NULL,'Active'),
(103,'Amit','Finance','Delhi',70000,7000,5,'2021-06-10',202,'Inactive'),
(104,'Priya','IT','Pune',85000,10000,7,'2019-11-05',201,'Active'),
(105,'John','Sales','Bangalore',40000,NULL,1,'2024-02-12',203,'Active'),
(106,'Riya','HR','Mumbai',50000,3000,4,'2020-07-18',NULL,'Inactive'),
(107,'Karan','IT','Hyderabad',95000,12000,8,'2018-09-25',201,'Active'),
(108,'Neha','Finance','Pune',65000,NULL,6,'2020-12-01',202,'Active'),
(109,'Arjun','Sales','Delhi',55000,4000,3,'2022-08-30',203,'Active'),
(110,'Pooja','IT','Mumbai',72000,5000,5,'2021-04-15',201,'Inactive');



SELECT * FROM EMPL_DATA;
SELECT EMP_NAME , SALARY FROM EMPL_DATA;
SELECT EMP_NAME,DEPARTMENT ,SALARY FROM EMPL_DATA WHERE DEPARTMENT='IT';
SELECT EMP_NAME ,SALARY FROM EMPL_DATA WHERE SALARY > 60000;
SELECT EMP_NAME , CITY FROM EMPL_DATA WHERE CITY = 'PUNE';
ALTER TABLE EMPL_DATA ADD INACTIVE_BOYS VARCHAR(100);

ALTER TABLE EMPL_DATA DROP INACTIVE_BOYS;

SELECT EMP_NAME ,STATUS FROM EMPL_DATA WHERE STATUS = 'ACTIVE';

SELECT EMP_NAME , SALARY FROM EMPL_DATA WHERE SALARY BETWEEN 50000 AND 80000;

SELECT EMP_NAME , DEPARTMENT FROM EMPL_DATA WHERE DEPARTMENT ='FINANCE' OR DEPARTMENT ='SALES';
SELECT EMP_NAME FROM EMPL_DATA WHERE EMP_NAME LIKE 'P%';

SELECT EMP_NAME,DEPARTMENT FROM EMPL_DATA WHERE DEPARTMENT <> 'FINANCE';





SELECT EMP_NAME ,BONUS FROM EMPL_DATA WHERE BONUS IS NULL;
SELECT EMP_NAME, count(*) FROM EMPL_DATA WHERE MANAGER_ID IS NULL;
SELECT *, coalesce(BONUS) FROM EMPL_DATA WHERE BONUS IS NULL;

UPDATE EMPL_DATA SET BONUS = 0 WHERE BONUS IS NULL;

SELECT SALARY, BONUS, SALARY+BONUS AS TOTAL_SALARY  FROM EMPL_DATA;

UPDATE EMPL_DATA SET BONUS = '200.00' WHERE BONUS = 0 ;
SELECT BONUS FROM EMPL_DATA WHERE BONUS IS NULL;

SELECT SALARY , SALARY * 12 AS ANNUAL_INCOME FROM EMPL_DATA;
SELECT SALARY , BONUS , SALARY + BONUS AS TOTAL_SALARY FROM EMPL_DATA;
SELECT EMP_NAME , EXPERIENCE FROM EMPL_DATA WHERE EXPERIENCE >= 5;
SELECT EMP_NAME , CITY,SALARY FROM EMPL_DATA WHERE CITY = 'PUNE' AND SALARY >= 70000;
SELECT * FROM EMPL_DATA WHERE STATUS ='ACTIVE' AND DEPARTMENT ='IT';
SELECT COUNT(*) FROM EMPL_DATA;
SELECT SUM(SALARY)AS TOTAL_SALARY FROM EMPL_DATA ;

SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY FROM EMPL_DATA GROUP BY DEPARTMENT;
SELECT SALARY  FROM EMPL_DATA ORDER BY SALARY desc LIMIT 1
SELECT MAX(SALARY)  FROM EMPL_DATA ;

SELECT MIN(SALARY) FROM EMPL_DATA ;
SELECT SUM(BONUS) AS TOTAL_BONUS FROM EMPL_DATA;
SELECT count(BONUS) AS RECEIVED_BONUS FROM EMPL_DATA;

UPDATE EMPL_DATA SET BONUS = NULL WHERE EMP_ID = 108;

SELECT COUNT(*) FROM EMPL_DATA where BONUS IS NULL;

SELECT EXPERIENCE,AVG(EXPERIENCE) FROM EMPL_DATA GROUP BY EXPERIENCE;
SELECT AVG(EXPERIENCE) FROM EMPL_DATA;

-- SALARY + BONUS = TOTAL ANNUAL SALARY 
SELECT SUM(SALARY+BONUS) AS TOTAL_ANNUAL FROM EMPL_DATA;
SELECT EMP_NAME ,JOIN_DATE FROM EMPL_DATA 
WHERE JOIN_DATE > '2022-08-31';

SELECT EMP_NAME ,EXPERIENCE FROM EMPL_DATA WHERE EXPERIENCE >5;
UPDATE EMPL_DATA SET BONUS = BONUS +1000 WHERE STATUS = 'ACTIVE';
UPDATE EMPL_DATA SET STATUS = 'INACTIVE' WHERE EXPERIENCE <= 2;  


SELECT SALARY-(SALARY *10) AS TAX_DEDUCT FROM EMPL_DATA ;
SELECT SUM(SALARY + coalesce(BONUS,0))  FROM EMPL_DATA ;

 -- ORDER BY DESC LIMIT 1 
 
 SELECT * FROM EMPL_DATA ORDER BY SALARY DESC LIMIT 1;
